<?php
/**
* @file
* A description of what your module does.
*/

include_once("Ecomonic.inc");

/**
 * Implements menu_hook().
 * @return array
 */
function economic_menu() {
    $item = array();

    //Admin configuration group
    $item["admin/config/economic"] = array(
        'title' => 'E-Conomic',
        'description' => 'Administer e-conomics settings',
        'access arguments' => array("user access")
    );

    //Admin configuration settings
    $item["admin/config/economic/manage"] = array(
        'title' => 'E-Conomic settings',
        'description' => 'Manage e-conomics settings',
        'access arguments' => array("user access"),
        'page callback' => 'drupal_get_form',
        'page arguments' => array("economic_admin_settings_form")
    );

    return $item;
}

/**
 * Implements hook_form()
 * @param $node
 * @param $form_state
 *
 * @return array
 */
function economic_admin_settings_form($node, &$form_state){
    $form = array();

    $form['overview'] = array(
        '#markup' => t("This interface allows you to manage general e-conomic settings"),
        '#prefix' => "<p>",
        '#suffix' => "</p>"
    );

    $form['economic_agreementnumber'] = array(
        '#title' => t("Agreement number"),
        '#type' => 'textfield',
        '#required' => true,
        '#default_value' => variable_get("economic_agreementnumber")
    );

    $form['economic_username'] = array(
        '#title' => t("Username"),
        '#type' => 'textfield',
        '#required' => true,
        '#default_value' => variable_get("economic_username")
    );

    $form['economic_password'] = array(
        '#title' => t("Password"),
        '#type' => 'textfield',
        '#required' => true,
        '#default_value' => variable_get("economic_password")
    );

    return system_settings_form($form);
}

/**
 * Implements hook_cron()
 */
function economic_cron(){
    try{
        $agreementnumber = variable_get("economic_agreementnumber");
        $username = variable_get("economic_username");
        $password = variable_get("economic_password");

        if($agreementnumber == "" || $username == "" || $password == ""){
            drupal_set_message(t("Specify e-conomic connection data"), "warning");
        }
        else{
            $economic = new Ecomonic($agreementnumber, $username, $password);
            $economic->connect();
            //fetch all economic users
            $debtorHandle = $economic->debtor_GetAll();

            foreach ($debtorHandle as $d) {
                $user = user_load($d->Number);
                $economic_user = $economic->debtor_GetData($d);
                $newuserdata = create_user_data($economic_user);
                //check ids in drupal
                //if does not exist
                if($user == false){
                    //add to drupal
                    user_save(null, $newuserdata);
                }else{
                    //if exists update data
                    //check if needs update
                    if(compare_user_data($user, $economic_user) == false)
                        user_save($user, $newuserdata);
                }
            }
            $economic->disconnect();
        }
    }
    catch(Exception $e){
        drupal_set_message($e->getMessage(), "error");
    }
}

/**
 * Compare drupal user and economic user for changes
 * @param $user
 * @param $economic_user
 *
 * @return bool
 * true if objects same. false if something changed
 */
function compare_user_data($user, $economic_user){
    if($user->uid               != $economic_user->Number)      return false;
    if($user->name              != $economic_user->Name)        return false;
    if($user->mail              != $economic_user->Email)       return false;
    if($user->data['address']   != $economic_user->Address)     return false;
    if($user->data['postalcode']!= $economic_user->PostalCode)  return false;
    if($user->data['city']      != $economic_user->City)        return false;
    if($user->data['country']   != $economic_user->Country)     return false;
    if($user->data['balance']   != $economic_user->Balance)      return false;
    return true;
}

/**
 * Creates user data array with values from economic user
 * @param $economic_user
 * @return array
 */
function create_user_data($economic_user){
    $newuser = array(
        'uid' => $economic_user->Number,
        'name' => $economic_user->Name,
        'pass' => generate_random_string(),
        'mail' => $economic_user->Email,
        'status' => 1,
        'data' => array(
            'address' => $economic_user->Address,
            'postalcode' => $economic_user->PostalCode,
            'city' => $economic_user->City,
            'country' => $economic_user->Country,
            'balance' => $economic_user->Balance
        )
    );
    return $newuser;
}

/**
 * Generates random character string
 * @param int $name_length
 * @return string
 */
function generate_random_string($name_length = 8) {
    $alpha_numeric = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return substr(str_shuffle($alpha_numeric), 0, $name_length);
}

/**
 * Implements hook_user_update().
 * @param $edit
 * @param $account
 * @param $category
 */
function economic_user_update(&$edit, $account, $category){
    try{
        $agreementnumber = variable_get("economic_agreementnumber");
        $username = variable_get("economic_username");
        $password = variable_get("economic_password");

        if($agreementnumber != "" && $username != "" && $password != ""){
            $economic = new Ecomonic($agreementnumber, $username, $password);
            $economic->connect();
            $userhandle = $economic->debtor_FindByNumber($account->uid);
            if(count(get_object_vars($userhandle)) == 0)
            {
                //user does not exist in economic add him
                $newuser = array(
                    'uid' => $account->uid,
                    'name' => $edit['name'],
                    'mail' => $edit['mail']
                );
                $economic->debtor_CreateFromData($newuser);
            }
            else{
                //get user
                $economic_user = $economic->debtor_GetData($userhandle);
                //check for data change
                $edit['uid'] = $account->uid;
                if(compare_user_data((object)$edit, $economic_user) == false){
                    //save to economic
                    $economic->debtor_SetName($userhandle, $edit['name']);
                    $economic->debtor_SetEmail($userhandle, $edit['mail']);
                }
            }
            $economic->disconnect();
        }
    }
    catch(Exception $e){
        //debug($e->getMessage(), 'error');
    }
}

/**
 * Implements hook_user_insert().
 * @param $edit
 * @param $account
 * @param $category
 */
function economic_user_insert(&$edit, $account, $category){
    try{
        $agreementnumber = variable_get("economic_agreementnumber");
        $username = variable_get("economic_username");
        $password = variable_get("economic_password");

        if($agreementnumber != "" && $username != "" && $password != ""){
            $economic = new Ecomonic($agreementnumber, $username, $password);
            $economic->connect();
            $userhandle = $economic->debtor_FindByNumber($account->uid);
            if(count(get_object_vars($userhandle)) == 0)
            {
                //user does not exist in economic add him
                $newuser = array(
                    'uid' => $account->uid,
                    'name' => $edit['name'],
                    'mail' => $edit['mail']
                );
                $economic->debtor_CreateFromData($newuser);
            }
            $economic->disconnect();
        }
    }
    catch(Exception $e){
        //debug($e->getMessage(), 'error');
    }
}